### ISSUE TITLE
doryen_rs merge

### ISSUE THREAD

**Issue by jice-nospam** [thebracket/bracket-lib#77]
I'm creating this issue to track work related to merging doryen_rs and bracket-lib.
Items that eventually require work in bracket-lib will have their dedicated issue.

**WASM**
* [ ]  MISSING cargo-web not supported. To be investigated

**Windowing**
* [ ] MISSING easy way to save a screenshot, like `BTerm::save_screenshot(file_path: &str)`

**Comment by thebracket** [comment]
Thanks for that! I'll see what I can do.

**Comment by thebracket** [comment]
_Re: Minimizing_
I've fixed the crash when minimized in commit ( https://github.com/thebracket/bracket-lib/commit/8be9576e245dc837a22ed9fd4f4205739b184666 ). I'm going to try and get a bunch put together before I build the next crate versions.

I'd love to have an option to pause the game loop when minimized, but it's going to be tough to make that work with back-ends other than OpenGL/native. There *might* be a hook for WASM, but I'm pretty sure Curses and Crossterm won't tell me if the parent terminal is minimized (I'll have to look in Amethyst; pretty sure I remember seeing that somewhere).

**Comment by thebracket** [comment]
*Re: not updating unless cls is called*

There's a new example, `no_cls` designed to catch this. It only calls a CLS if you press `C`, otherwise, it just keeps adding to the terminals. In the current builds, it's working well for me - the parent issue (82) is "pending confirmation".

**Comment by thebracket** [comment]
*Re: WASM not working*

The current MASTER build (now includes local paths for easier building) is compiling fine for me, now. There was an issue with some code from a PR not updating the WASM tree correctly. I'm pretty sure that one is fixed.

**Comment by jice-nospam** [comment]
I still can't make WASM target work. I'm using a cloned bracket-lib on master and run : 
```shell
> cd bracket-lib/bracket-terminal
> cargo web start --example keyboard
```
I'm using the latest rust 1.41.1 and cargo-web 0.6.26 and tested on both firefox 73.0.1 and chromium 69.0. I get the same error in both :

```Error loading Rust wasm module 'basic': TypeError: WebAssembly Instantiation: Import #0 module="__wbindgen_placeholder__" error: module is not an object or function```

What is it you're doing something different from me ?

**Comment by jice-nospam** [comment]
Concerning the new input API, I'm back to my previous issue. Providing the existing doryen-rs API using bracketlib would require to copy all input state from bracketlib to another object because I can't pass the `&mut BTerm` reference around.

```rust
impl Doryen {
    // function called by the users of doryen-rs library
    pub fn key_pressed(scan_code: u32) -> bool {
        // can't do that without a reference to &mut BTerm
        // or having all BTerm state copied in Doryen
    }
}
impl GameState for Doryen {
    fn tick(&mut self, ctx: &mut BTerm) {
        ...
    }
}
```

There may be other solutions, but passing a Rc<RefCell<BTerm>> in tick would work:
```rust
impl Doryen {
    pub fn key_pressed(scan_code: u32) -> bool {
        self.ctx.borrow().input.is_scancode_pressed(scan_code)
    }
}
impl GameState for Doryen {
    fn tick(&mut self, ctx: Rc<RefCell<BTerm>>) {
        self.ctx=ctx.clone();
    }
}
```

**Comment by Zireael07** [comment]
Tangential, I just discovered glow does support WebGL 1 context and that floating point framebuffer isn't explicitly an WebGL2 thing... could we maybe get a fallback to WebGL1, please, for people stuck with MS Edge?

**Comment by thebracket** [comment]
The `input_api` has been merged, forgot to tag the merge commit.

**Comment by thebracket** [comment]
The last bundle of commits added:

* Right aligned printing via context and command buffer.
* Centered with an arbitrary center point printing via context and command buffer.
* A new `printer` command that looks a whole like `doryen_rs`'s printing format.

**Comment by thebracket** [comment]
Virtual Terminals are kind-of a compromise. I needed a way to handle consoles much bigger than the screen and view "windows" into them. `Doryen_rs` needed a way to make sub-consoles. So a `VirtualConsole` can do both: it can be of any, arbitrary size (including reading large amounts of text; I had a need for that for manual files).

It isn't "owned" or "attached" to a real console in any way - so you can make it and keep it around, without having it touch the underlying engine state until you need it.

Submission (via render batch or direct to context) works on any target console (whatever is active). So if you have multiple layers, you can splat it to a sparse top layer and have it partially apply (alpha isn't supported yet) - ideal for putting your HUD onto the screen. If a glyph has a value of 0, it isn't copied: so you can leave holes in it if you want to.

Once sparse consoles support alpha (it doesn't make any sense for the base console to support it), this will let you put nicely faded elements such as tool-tips on top of your main display (on systems that support alpha, obviously).

**Comment by thebracket** [comment]
The `rgba` branch is tracking progress on using RGBA and supporting alpha (on terminals that support it). The API is present but not as friendly as I'd like, yet (getting there). I have alpha blending working on a sparse console, native GL only in the new `alpha` example.

**Comment by thebracket** [comment]
I forgot to mention that `bracket-lib` has supported non-greyscale fonts from the beginning, but it wasn't entirely obvious. Now that RGBA/alpha is baked in, it does it better! In the `rgba` branch, there's a new example called `colorfont` (try it online: https://bfnightly.bracketproductions.com/wasmtest/colorfont/ ) that does a better job of showing it. I took the VGA 8x16 font, applied a gradient to it in The Gimp, and used a blur filter to anti-alias the edges so they have some alpha content.

The same setup is used for the tiles example: https://bfnightly.bracketproductions.com/wasmtest/tiles/

Font files still have to be arranged 16 tiles per row, with 16 rows (to give 255 characters) - but they can be anything you want (you'll wind up accessing them by number). I'll see about relaxing that restriction and improving the mapping in a future update. I have a few related ideas I've been bouncing around, so it'll be a feature branch once `rgba` is wrapped. (It's getting close; I'm just finishing up "set all alpha" functions to mass-set fg/bg/all on a layer, and improving `bracket-color` handling of alpha options and conversion paths)

**Comment by thebracket** [comment]
RGBA is now merged. I added more conversions and unit testing to `bracket-color`, and benchtests showed performance is about the same as before even with the `try` stuff.

**Comment by jice-nospam** [comment]
I'm closing this as pretty much all the major features have been imported to bracket-lib. What an amazing coding spree ! Congratulations :)
